name: play_it_later
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.7
  - pip
  - jupyter
  - notebook
  - setuptools
  - pip:
      - cryptography
      - beautifulsoup4
      - flask
      - colorama
      - selenium
      - click
      - pyperclip
      - requests
      - cython
      - easydict
      - matplotlib
      - jupyter_console
      - webdriver-manager
      - jupyterlab
      - nbdev
      - jupyter
      - jupyterthemes
      - fastcore