# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"process_dirs": "00_encryption.ipynb",
         "encrypt_file": "00_encryption.ipynb",
         "pv": "00_encryption.ipynb",
         "decrypt_file": "00_encryption.ipynb",
         "txt2encrypted_file": "01_talker.ipynb",
         "encrypted_file2txt": "01_talker.ipynb",
         "HttpConnectionFailure": "01_talker.ipynb",
         "send_encryption_key": "01_talker.ipynb",
         "request_decryption_key": "01_talker.ipynb"}

modules = ["encryption.py",
           "talker.py"]

doc_url = "https://josiahls.github.io/play_it_later/"

git_url = "https://github.com/josiahls/play_it_later/tree/master/"

def custom_doc_links(name): return None
